// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDinKtcIwG3eRJvwmfeQcC1ibqFMfEfWIs',
    appId: '1:1066417215342:web:d26b16e72945340786537f',
    messagingSenderId: '1066417215342',
    projectId: 'tutorpro-f9aa3',
    authDomain: 'tutorpro-f9aa3.firebaseapp.com',
    storageBucket: 'tutorpro-f9aa3.firebasestorage.app',
    measurementId: 'G-1BBVYEL5PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaIqYozHhKJy_4UAosnk46lwztLh6Nw6Q',
    appId: '1:1066417215342:android:b46debaccbe3141086537f',
    messagingSenderId: '1066417215342',
    projectId: 'tutorpro-f9aa3',
    storageBucket: 'tutorpro-f9aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPwI-tbTYUpJe1NtgS2Xn_MyLdB2ag8ic',
    appId: '1:1066417215342:ios:47476f4e6149d5f086537f',
    messagingSenderId: '1066417215342',
    projectId: 'tutorpro-f9aa3',
    storageBucket: 'tutorpro-f9aa3.firebasestorage.app',
    iosBundleId: 'com.example.tutorpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPwI-tbTYUpJe1NtgS2Xn_MyLdB2ag8ic',
    appId: '1:1066417215342:ios:47476f4e6149d5f086537f',
    messagingSenderId: '1066417215342',
    projectId: 'tutorpro-f9aa3',
    storageBucket: 'tutorpro-f9aa3.firebasestorage.app',
    iosBundleId: 'com.example.tutorpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDinKtcIwG3eRJvwmfeQcC1ibqFMfEfWIs',
    appId: '1:1066417215342:web:93e4127dccf6084486537f',
    messagingSenderId: '1066417215342',
    projectId: 'tutorpro-f9aa3',
    authDomain: 'tutorpro-f9aa3.firebaseapp.com',
    storageBucket: 'tutorpro-f9aa3.firebasestorage.app',
    measurementId: 'G-0RGNFN68HL',
  );
}
